org: orangemge
app: aws-lambda-weather-app
service: aws-lambda-weather-app
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

functions:
  getWeather:
    handler: src/getWeather.getWeather
    events:
      - http:
          path: /weather/{city}
          method: get